gcp_project            = "entur-1287"
pubsub_project            = "entur-ror-prod"
storage_project            = "entur-ror-prod"
kube_namespace = "production"
bucket_instance_suffix ="production"
location = "europe-west1"
service_account_bucket_role="roles/storage.admin"
bucket_instance_prefix="irkalla"