kube_namespace = "irkalla"
pubsub_project = "ent-irkalla-prd"
storage_project = "ent-irkalla-prd"
location = "europe-west1"
bucket_instance_suffix = "prd"
tiamat-changelog-topic ="projects/ent-tiamat-prd/topics/ror.tiamat.changelog"