kube_namespace = "irkalla"
pubsub_project = "ent-irkalla-tst"
storage_project = "ent-irkalla-tst"
location = "europe-west1"
bucket_instance_suffix = "tst"
tiamat-changelog-topic ="projects/ent-tiamat-tst/topics/ror.tiamat.changelog"